################################################################################################################################
# Information sur le site #
###########################
# Auteur du site
author: Marc Jaffré

# Avatar du site
avatar: "https://avatars.githubusercontent.com/u/35907?v=4"

# Désactiver l'avatar en rond
round-avatar: false

# Description du site
description: Documentation par Marc Jaffré

# Theme du site
theme: jekyll-theme-minimal

# Nom du Site
title: Drthrax74


################################################################################################################################
# Gestion du menu #
###################
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Accueil de l'auteur: "https://dexter74.github.io/"
